name: h2oGPTe Agent
description: Use h2oGPTe's agent coding capabilties directly in GitHub.
author: H2O.ai

branding:
  icon: droplet
  color: yellow

inputs:
  github_token:
    description: GitHub Access Token. Should be defined via a repository secret.
    required: true
  h2ogpte_api_key:
    description: h2oGPTe API Key from https://h2ogpte.genai.h2o.ai/api. Should be defined via a repository secret.
    required: true
  h2ogpte_api_base:
    description: h2oGPTe API base url address (no trailing slash). By default, it is set to https://h2ogpte.genai.h2o.ai.
    required: false
    default: https://h2ogpte.genai.h2o.ai
  github_api_url:
    description: GitHub API base url (no trailing slash). By default, it is set to https://api.github.com.
    required: false
    default: https://api.github.com
  github_server_url:
    description: GitHub server base url (no trailing slash). By default, it is set to https://github.com.
    required: false
    default: https://github.com
  # h2oGPTe Configuration
  llm:
    description: Language model to use (by default, h2oGPTe will select the best available model for the task)
    required: false
    default: "auto"
  agent_max_turns:
    description: Maximum number of turns the agent can take (must be one of {"auto", 5, 10, 15, 20})
    required: false
    default: "auto"
  agent_accuracy:
    description: Agent accuracy setting (must be one of {"quick", "basic", "standard", "maximum"})
    required: false
    default: "standard"
  agent_total_timeout:
    description: Total timeout in seconds for all agent processing.
    required: false
    default: "3600"
  prompt:
    description: Prompt for custom workflow. String injection options are {{repoName}}, {{idNumber}} and {{eventsText}}, see README.md for more details.
    required: false
  slash_commands:
    description: JSON string defining slash commands. Each command should have a name and prompt field.
    required: false
  collection_id:
    description: Collection to use for the agent (by default, a new collection will be created for each run)
    required: false
  guardrails_settings:
    description: Configuration for input/output control of Personal Identifiable Information (PII) and harmful content generation. For more information https://docs.h2o.ai/enterprise-h2ogpte/guide/collections/pii-sanitization
    required: false

runs:
  using: composite
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # https://github.com/oven-sh/setup-bun/releases/tag/v2.0.2
      with:
        bun-version: 1.2.15

    - name: Install Dependencies
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        bun install

    - name: Run Action
      shell: bash
      run: |
        bun run ${GITHUB_ACTION_PATH}/src/entrypoint.ts
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_API_URL: ${{ inputs.github_api_url }}
        GITHUB_SERVER_URL: ${{ inputs.github_server_url }}
        H2OGPTE_API_KEY: ${{ inputs.h2ogpte_api_key }}
        H2OGPTE_API_BASE: ${{ inputs.h2ogpte_api_base }}
        # h2oGPTe Configuration
        LLM: ${{ inputs.llm }}
        AGENT_MAX_TURNS: ${{ inputs.agent_max_turns }}
        AGENT_ACCURACY: ${{ inputs.agent_accuracy }}
        AGENT_TOTAL_TIMEOUT: ${{ inputs.agent_total_timeout }}
        PROMPT: ${{ inputs.prompt }}
        SLASH_COMMANDS: ${{ inputs.slash_commands }}
        COLLECTION_ID: ${{ inputs.collection_id }}
        GUARDRAILS_SETTINGS: ${{ inputs.guardrails_settings }}
