name: h2oGPTe Agent
description: Use h2oGPTe's agent coding capabilties directly in GitHub.
author: H2O.ai

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  github_token:
    description:
      Github access token. In the future, we should be able to create one in the
      action.
    required: true
  h2ogpte_api_key:
    description: h2oGPTe API Key from https://h2ogpte.internal.dedicated.h2o.ai
    required: true
  h2ogpte_api_base:
    description: h2oGPTe API base url address (no trailing slash)
    required: false
    default: https://h2ogpte.internal.dedicated.h2o.ai
  github_api_url:
    description: github api base url (no trailing slash)
    required: false
    default: https://api.github.com
  github_server_url:
    description: github server base url (no trailing slash)
    required: false
    default: https://github.com
  # h2oGPTe Configuration
  llm:
    description: Language model to use (e.g., "llama3.2-70b-instruct", "mistral-7b-instruct")
    required: false
    default: "auto"
  agent_max_turns:
    description: Maximum number of turns the agent can take (must be one of {"auto", 5, 10, 15, 20})
    required: false
    default: "auto"
  agent_accuracy:
    description: Agent accuracy setting (must be one of {"quick", "basic", "standard", "maximum"})
    required: false
    default: "standard"

runs:
  using: composite
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # https://github.com/oven-sh/setup-bun/releases/tag/v2.0.2
      with:
        bun-version: 1.2.15

    - name: Install Dependencies
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        bun install

    - name: Run Action
      shell: bash
      run: |
        bun run ${GITHUB_ACTION_PATH}/src/entrypoint.ts
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_API_URL: ${{ inputs.github_api_url }}
        GITHUB_SERVER_URL: ${{ inputs.github_server_url }}
        H2OGPTE_API_KEY: ${{ inputs.h2ogpte_api_key }}
        H2OGPTE_API_BASE: ${{ inputs.h2ogpte_api_base }}
        # h2oGPTe Configuration
        LLM: ${{ inputs.llm }}
        AGENT_MAX_TURNS: ${{ inputs.agent_max_turns }}
        AGENT_ACCURACY: ${{ inputs.agent_accuracy }}
