name: h2oGPTe Agent
description: Use h2oGPTe's agent coding capabilties directly in GitHub.
author: H2O.ai

branding:
  icon: droplet
  color: yellow

inputs:
  github_token:
    description: GitHub Access Token. Should be defined via a repository secret.
    required: true
  h2ogpte_api_key:
    description: h2oGPTe API Key from https://h2ogpte.genai.h2o.ai/api. Should be defined via a repository secret.
    required: true
  h2ogpte_api_base:
    description: h2oGPTe API base url address (no trailing slash). By default, it is set to https://h2ogpte.genai.h2o.ai.
    required: false
    default: https://h2ogpte.genai.h2o.ai
  github_api_url:
    description: GitHub API base url (no trailing slash). By default, it is set to https://api.github.com.
    required: false
    default: https://api.github.com
  github_server_url:
    description: GitHub server base url (no trailing slash). By default, it is set to https://github.com.
    required: false
    default: https://github.com
  # h2oGPTe Configuration
  llm:
    description: Language model to use (by default, h2oGPTe will select the best available model for the task)
    required: false
    default: "auto"
  agent_max_turns:
    description: Maximum number of turns the agent can take (must be one of {"auto", 5, 10, 15, 20})
    required: false
    default: "auto"
  agent_accuracy:
    description: Agent accuracy setting (must be one of {"quick", "basic", "standard", "maximum"})
    required: false
    default: "standard"
  agent_total_timeout:
    description: Total timeout in seconds for all agent processing.
    required: false
    default: "3600"
  prompt:
    description: Prompt for custom workflow. String injection options are {{repoName}}, {{idNumber}} and {{eventsText}}, see README.md for more details.
    required: false
  # Slash Commands Configuration
  slash_commands:
    description: JSON string defining slash commands. Each command should have a name and prompt field.
    required: false
    default: |
      [
        {
          "name": "/explain",
          "prompt": "You are an expert software engineer and technical writer. Your job is to clearly and accurately explain code to the user.\n\nYou are given:\n1. A code snippet.\n2. A user prompt potentially containing context or questions.\n\nYour task:\n- Provide a concise but thorough explanation of what the code does.\n- Explain the logic, flow, data transformations, and intent.\n- Highlight any non-obvious behaviour, side effects, performance characteristics, or edge cases.\n- If relevant, explain how the code fits into the broader system based on the user's prompt.\n- Avoid making code changes or suggestions unless the user explicitly asks.\n- Use simple, direct language aimed at a software engineer.\n\nOutput should be easy to skim with short paragraphs, bullet points, and clear structure."
        },
        {
          "name": "/review",
          "prompt": "You are an expert software engineer performing a high-quality code review. You are given:\n1. A code snippet.\n2. A user prompt with context or goals.\n\nYour task:\n- Review the code for correctness, readability, maintainability, performance, and potential bugs.\n- Reference specific lines or behaviours when giving feedback.\n- Identify potential risks, edge cases, antipatterns, or missing tests.\n- Provide constructive, actionable feedback.\n- Suggest improvements that align with best practices and the user’s stated goals.\n- Do NOT rewrite any code unless explicitly asked.\n\nBe structured and professional. Organise feedback into sections such as 'Strengths', 'Areas for Improvement', etc."
        },
        {
          "name": "/plan",
          "prompt": "You are an expert software engineer and solution architect. You are given a user prompt describing requirements or a desired feature.\n\nYour task:\n- Produce a clear, actionable plan for how you would implement the requested functionality.\n- Break down the work into logical steps, components, or modules.\n- Cover architecture, data flow, APIs, edge cases, and testing strategy where relevant.\n- Keep the plan implementation-agnostic unless the user specifies a particular stack or language.\n- DO NOT write or modify any code.\n- DO NOT output code blocks.\n\nReturn a structured plan with headings, bullets, and concise explanations."
        }
      ]

runs:
  using: composite
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # https://github.com/oven-sh/setup-bun/releases/tag/v2.0.2
      with:
        bun-version: 1.2.15

    - name: Install Dependencies
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        bun install

    - name: Run Action
      shell: bash
      run: |
        bun run ${GITHUB_ACTION_PATH}/src/entrypoint.ts
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_API_URL: ${{ inputs.github_api_url }}
        GITHUB_SERVER_URL: ${{ inputs.github_server_url }}
        H2OGPTE_API_KEY: ${{ inputs.h2ogpte_api_key }}
        H2OGPTE_API_BASE: ${{ inputs.h2ogpte_api_base }}
        # h2oGPTe Configuration
        LLM: ${{ inputs.llm }}
        AGENT_MAX_TURNS: ${{ inputs.agent_max_turns }}
        AGENT_ACCURACY: ${{ inputs.agent_accuracy }}
        AGENT_TOTAL_TIMEOUT: ${{ inputs.agent_total_timeout }}
        PROMPT: ${{ inputs.prompt }}
        # Slash Commands Configuration
        SLASH_COMMANDS: ${{ inputs.slash_commands }}
