name: Task
description: Track a specific task or action item
labels: [task]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Task
        Please describe the task to be completed.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short summary of the task
      placeholder: e.g. Update documentation for API v2
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Additional details or context
  - type: input
    id: due-date
    attributes:
      label: Due Date
      description: When should this task be completed? (optional)
      placeholder: e.g. 2025-09-10
