name: h2oGPTe Agent Automatic Documentation

on:
  pull_request:
    branches: [main]
    types: [opened]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  h2ogpte-agent-assistant:
    name: h2oGPTe Auto Docs Agent
    runs-on: ubuntu-latest

    steps:
      - name: h2oGPTe Auto Docs Agent
        id: h2ogpte-agent-assistant
        uses: h2oai/h2ogpte-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          h2ogpte_api_key: ${{ secrets.H2OGPTE_API_KEY }}
          # h2oGPTe Configuration (optional)
          llm: "auto" # choose from: https://docs.h2o.ai/enterprise-h2ogpte/guide/models-section
          agent_max_turns: "auto" # agent_max_turns must be one of: {"auto", 5, 10, 15, 20}
          agent_accuracy: "standard" # agent_accuracy must be one of: {"quick", "basic", "standard", "maximum"}
          agent_total_timeout: 3600 # agent_total_timeout must be a positive integer in seconds
          prompt:
            | # Prompt for the pull request review. Injects string literals {repoName}, {idNumber} and {eventsText}.
            You must only generate documentation for the user's repository, {repoName} on pull request number {idNumber}.

            Then read the code changes in the pull request and understand the context of the code changes.
            Once you have a good understanding of the context, you can begin to generate documentation.
            Ensure you understand all existing documentation in the code changes so far and don't overwrite it.
            If the changes are trivial, you can skip the documentation generation.

            Here are the previous events in chronological order:
            {eventsText}

            Ensure that you don't change any code in the pull request.
            You can work on the documentation in the user's repository, mainly docstrings, comments and readme files.
            Keep a record of all the changes you make to the documentation and comment them at the end. Do not create any new files regarding the changes made.
