name: h2oGPTe Agent Assistant

on:
  issues:
    types: [opened, assigned]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  h2ogpte-agent-assistant:
    name: h2oGPTe Agent Assistant
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issues' && contains(github.event.issue.body, '@h2ogpte')) ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@h2ogpte')) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.body, '@h2ogpte')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@h2ogpte')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@h2ogpte'))

    steps:
      - name: h2oGPTe Agent Assistant
        id: h2ogpte-agent-assistant
        uses: h2oai/h2ogpte-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          h2ogpte_api_key: ${{ secrets.H2OGPTE_API_KEY }}
