name: h2oGPTe Agent Automatic Review

on:
  pull_request:
    branches: [main]
    types: [opened]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  h2ogpte-auto-review:
    name: h2oGPTe Auto Review Agent
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: h2oGPTe Auto Review Agent
        id: h2ogpte-auto-review
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          h2ogpte_api_key: ${{ secrets.H2OGPTE_API_KEY }}
          prompt:
            | # Prompt for the pull request review. Injects string literals {repoName}, {idNumber} and {eventsText}.
            You must only review in the user's repository, {repoName} on pull request number {idNumber}.

            First read the previous events and understand the context of the pull request provided below.
            Then read the code changes in the pull request and understand the context of the code.
            Once you have a good understanding of the context, you can begin to review the code.

            Here are the previous events in chronological order:
            {eventsText}

            Do not create any comments on the pull request yourself or change any code in the pull request.
            You must only return your code review.
