name: h2oGPTe Agent Automatic Review

on:
  pull_request:
    branches: [main]
    types: [opened]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  h2ogpte-auto-review:
    name: h2oGPTe Auto Review Agent
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: h2oGPTe Auto Review Agent
        id: h2ogpte-auto-review
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          h2ogpte_api_key: ${{ secrets.H2OGPTE_API_KEY }}
          prompt: |
            You must only review in the user's repository, {{repoName}} on pull request number {{idNumber}}.

            First read the previous events and understand the context of the pull request provided below.
            Then read the code changes in the pull request and understand the context of the code.
            Once you have a good understanding of the context, you can begin to review the code.

            Here are the previous events in chronological order:
            {{eventsText}}

            Create a comment documenting your review in a concise manner.
            Do not create any new commits, rather describe the relevant required code changes for the user to implement.
