name: Release Dry Run

on:
  workflow_dispatch:

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if remote tag exists
        id: check_remote_tag
        run: |
          TAG="v${{ steps.get_version.outputs.version }}"
          if git ls-remote --tags origin "refs/tags/$TAG" | grep -q .; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Write summary
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          TAG="v$VERSION"
          EXISTS="${{ steps.check_remote_tag.outputs.exists }}"
          {
            echo "## Release Dry Run"
            echo ""
            echo "**Current version:** \`$VERSION\`"
            echo "**Tag to be created:** \`$TAG\`"
            if [ "$EXISTS" = "true" ]; then
              echo ":x: **Tag already exists - ensure the version is correctly bumped!**"
            else
              echo ":white_check_mark: **Tag doesn't already exist and can be created.**"
            fi
          } >> $GITHUB_STEP_SUMMARY
