name: Release Dry Run

on:
  workflow_dispatch:

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: get_version
        run: echo "version=$(node -p 'require(\"./package.json\").version')" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check_tag
        run: |
          TAG="v${{ steps.get_version.outputs.version }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Write summary
        run: |
          VERSION="${{ steps.get_version.outputs.version }}"
          TAG="v$VERSION"
          EXISTS="${{ steps.check_tag.outputs.exists }}"
          {
            echo "## Release Dry Run"
            echo ""
            echo "**Current version:** \`$VERSION\`"
            echo "**Tag to be created:** \`$TAG\`"
            if [ "$EXISTS" = "true" ]; then
              echo ":x: **Tag already exists!**"
            else
              echo ":white_check_mark: **Tag does not exist and can be created.**"
            fi
          } >> $GITHUB_STEP_SUMMARY
